### ISSUE TITLE
Side bar broken / tests not working

### ISSUE THREAD

**Issue by ChillyBots** [Codium-ai/codiumai-vscode-release#102]
Plugin version 0.7.8

Hi, I've previously been using the side panel for generating tests, as the test generation UI that pops up in a tab can be overwhelming and overtakes my dev environment. However, the sidebar seems to have only the chat panel:

![image](https://github.com/Codium-ai/codiumai-vscode-release/assets/80390882/0222f2f5-91cc-4bd4-ae3d-61a2e305e504)

Do you know how I can get it back? I can confirm the sidebar is still there in 0.7.7 but it seems to not generate any tests

**Comment by EdenChar** [comment]
Sadly the side panel has changed with the latest update. And this new version doesn't really help. The old one was much better and practical.

**Comment by almog-lv** [comment]
Hello @EdenChar and @ChillyBots 
As we progress, we listen to our users and try to improve the experience.
I understand the previous sidebar was convenient for you to use, but it had some issues, and we got some complaints about the usage. The new chat interface has all the capabilities of the previous panel except generating tests that are handled in our right sidebar. 
Also, we are improving the test generation flow these days so that you can get better quality tests and, later on, more test types. This cannot work with our previous sidebar. 
But I understand you liked the "simple" test generation, so we are also considering doing something similar from the chat itself. If you'd like to share more, you can do it here or in our Discord community
