### ISSUE TITLE
Tests not displaying after Codium's latest vscode extension update

### ISSUE THREAD

**Issue by xshapira** [Codium-ai/codiumai-vscode-release#7]
After the latest update to the vscode extension, Codium isn't displaying the tests that need to be generated.

![Screen Shot 1](https://user-images.githubusercontent.com/48856190/225511676-2bfb20ee-a4b5-4275-a812-057063260987.JPG)

┆Issue is synchronized with this [Trello card](https://trello.com/c/ZamjeXbt) by [Unito](https://www.unito.io)

**Comment by oranshiner** [comment]
Hey max,
Thank you for reporting the issue, We tried to reproduce the problem and we were not successful so I have a few questions that might help us check the issue, could you please close the app and reopen and click on the Codium logo on the bottom right corner to see that you are logged in, then check again, if you still don't see the buttons to generate tests maybe try another file to check that the problem is not with this specific functions, are you connected to our discord channel so we can talk to you directly

Thank you
Oran
